apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Release.Namespace }}
data:
  REDIS_ENABLED: {{ .Values.app.redis.enabled | quote }}
  REDIS_HOST: "{{ .Release.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local"
  REDIS_PORT: "6379"
  DB_HOST: "{{ .Release.Name }}-rw.{{ .Release.Namespace }}.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: {{ .Release.Name | quote }}
  {{- range $key, $val := .Values.app.backend.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
