apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.app.cnpg.clusterName }}-rw.{{ .Release.Namespace }}.svc.cluster.local 5432; do
                echo "Waiting for PostgreSQL..."; sleep 2
              done
      containers:
        - name: backend
          image: "{{ .Values.app.backend.image.repository }}:{{ .Values.app.backend.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.app.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-backend-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.app.cnpg.clusterName }}-app"
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.app.cnpg.clusterName }}-app"
                  key: password
          readinessProbe:
            httpGet:
              path: {{ .Values.app.backend.healthPath }}
              port: {{ .Values.app.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.app.backend.healthPath }}
              port: {{ .Values.app.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
