apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
  namespace: {{ .Values.app.namespace }}
spec:
  type: {{ .Values.app.frontend.service.type }}
  selector:
    app: {{ .Values.app.name }}-frontend
  ports:
    - name: http
      port: {{ .Values.app.frontend.port }}
      targetPort: {{ .Values.app.frontend.port }}
      {{- if eq .Values.app.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.app.frontend.service.port }}
      {{- end }}
