{{- if .Values.testing.loadTesting.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-load-test-backend
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.testing.loadTesting.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          metadata:
            labels:
              app: {{ .Release.Name }}-load-test-backend
          restartPolicy: Never
          containers:
            - name: load-test-backend
              image: {{ .Values.testing.loadTesting.scriptImage }}
              env:
                - name: BACKEND_HOST
                  value: "{{ .Release.Name }}-backend"
                - name: BACKEND_PORT
                  value: {{ .Values.app.backend.port | quote }}
{{- end }}
