{{- if .Values.app.redis.enabled }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: {{ .Values.app.name }}-redis
  namespace: {{ .Values.app.namespace }}
spec:
  kubernetesConfig:
    image: {{ .Values.app.redis.image }}
    imagePullPolicy: IfNotPresent
  redisConfig:
    additionalRedisConfig: "loglevel verbose"
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.app.redis.storage }}
{{- end }}
